(Bulletin {month:"March", year:2025})
    └── [:HAS_CHANGE]
        └── (Change {category:"Fraud", title:"Fraud Liability Shift"})
              ├── [:ASSIGNED_TO] -> (Team {name:"Fraud Management"})
              ├── [:TRACKED_BY]  -> (Task {status:"Pending"})
              └── [:SIMILAR_TO]  -> (Change from Feb 2025 bulletin)
