from RAGaaS.logs.logging_setup   import LogUtil, LogType, LogLevel


def create_bronze(spark, bronze_table_name):
    spark.sql(
        f"""
    CREATE TABLE IF NOT EXISTS {bronze_table_name} (
    input_file STRING,
    modificationTime TIMESTAMP,
    length BIGINT,
    content BINARY,
    datetime TIMESTAMP,
    file_hash STRING
    ) TBLPROPERTIES (delta.enableChangeDataFeed = true)
            """
    )
    
    LogUtil.log(LogType.TRANSACTION, LogLevel.INFO,'Bronze table created successfully')


def create_silver(spark, silver_table_name):
    spark.sql(
        f"""
    CREATE TABLE IF NOT EXISTS {silver_table_name} (
    input_file STRING,
    file_hash STRING,
    page_nr STRING,
    page_content STRING,
    document_name STRING,
    datetime TIMESTAMP,
    article_id STRING,
    publication_date STRING,
    effective_date STRING
    ) TBLPROPERTIES (delta.enableChangeDataFeed = true)
            """
    )
    LogUtil.log(LogType.TRANSACTION, LogLevel.INFO,'Silver table created successfully')


def create_gold(spark, gold_table_name):

    spark.sql(
        f"""
    CREATE TABLE IF NOT EXISTS {gold_table_name} (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START with 1 INCREMENT by 1),
    input_file STRING,
    file_hash STRING,
    page_nr STRING,
    document_name STRING,
    content_chunk STRING,
    datetime TIMESTAMP,
    page_content STRING
    ) TBLPROPERTIES (delta.enableChangeDataFeed = true)
            """
    )

    LogUtil.log(LogType.TRANSACTION, LogLevel.INFO,'Gold table created successfully')
